## This notebook contains the Data PreparationTask!

- NB: This work was done on a windows machine!

<hr style="height:20px">

### Importing the needed python libraries

In [1]:
import time

import pandas as pd
import numpy as np

In [2]:
## To get programm start time

start_time = time.time()
start_time

1641851403.384368

### Reading the data using read_pickle() + data exploration!

In [3]:
# Read the cases dataframe 

cases_df = pd.read_pickle(r"..\data\df_cases_200906.gzip")
cases_df.shape

(2069, 8)

In [4]:
# Show the top five rows in df1!

cases_df.head()

,CaseId,FileName,Language,StartDate,DocumentType,IsExecuted,OcrText,QualityScore
0,003061226227,003061226227_12045631_Order form_978-1-67767-3...,EN,20191104,Order form,False,Pressure style response character.,0.649292
1,003061226383,003061226383_63912371_Contract Info Pack_978-0...,EN,20190805,Contract Info Pack,False,Soon especially boy thousand traditional.,0.873038
2,003061226383,003061226383_41775424_other documents_978-1-38...,EN,20190805,other documents,True,Tax south say strategy hard between late.,0.991280
3,003061227777,003061227777_96463321_other documents_978-1-96...,EN,20191231,other documents,False,Yet arm six design.,0.607833
4,003061227781,003061227781_62201704_other documents_978-1-04...,EN,20191231,other documents,False,Plan camera actually run push rest.,0.909359

In [5]:
# Read the labels dataframe 

labels_df = pd.read_pickle(r'..\data\df_label_200906.gzip')
labels_df.shape

(1098, 3)

In [6]:
# Show the top five rows in df2!

labels_df.head()

         CaseId label_1 label_2
0  003061226227   False   False
1  003061226383    True   False
2  003061227777   False   False
3  003061227781   False   False
4  003061227680    True    True

### Begin of Data_Preparation

In [7]:
#Joining the two dataframes into one, based on CaseId!

df_final = pd.merge(cases_df, labels_df, on=['CaseId'])
df_final.shape

(2069, 10)

In [8]:
# Show the top five rows in df_final after merge!

df_final.head()

,CaseId,FileName,Language,StartDate,DocumentType,IsExecuted,OcrText,QualityScore,label_1,label_2
0,003061226227,003061226227_12045631_Order form_978-1-67767-3...,EN,20191104,Order form,False,Pressure style response character.,0.649292,False,False
1,003061226227,003061226227_78482906_other documents_978-0-25...,EN,20191104,other documents,True,Wrong to very edge create.,0.919028,False,False
2,003061226227,003061226227_04034216_Order form_978-1-83411-5...,EN,20191104,Order form,True,How serious approach another security fish inc...,0.707813,False,False
3,003061226383,003061226383_63912371_Contract Info Pack_978-0...,EN,20190805,Contract Info Pack,False,Soon especially boy thousand traditional.,0.873038,True,False
4,003061226383,003061226383_41775424_other documents_978-1-38...,EN,20190805,other documents,True,Tax south say strategy hard between late.,0.991280,True,False

#### To get rid of some uneeded columns: Language, StartDate and DocumentType!

In [9]:
#delete Language
if 'Language' in df_final.columns:
    del df_final['Language']

In [10]:
#delete StartDate
if 'StartDate' in df_final.columns:
    del df_final['StartDate']

In [11]:
#delete DocumentType
if 'DocumentType' in df_final.columns:
    del df_final['DocumentType']

In [12]:
df_final.head(10)

,CaseId,FileName,IsExecuted,OcrText,QualityScore,label_1,label_2
0,003061226227,003061226227_12045631_Order form_978-1-67767-3...,False,Pressure style response character.,0.649292,False,False
1,003061226227,003061226227_78482906_other documents_978-0-25...,True,Wrong to very edge create.,0.919028,False,False
2,003061226227,003061226227_04034216_Order form_978-1-83411-5...,True,How serious approach another security fish inc...,0.707813,False,False
3,003061226383,003061226383_63912371_Contract Info Pack_978-0...,False,Soon especially boy thousand traditional.,0.873038,True,False
4,003061226383,003061226383_41775424_other documents_978-1-38...,True,Tax south say strategy hard between late.,0.991280,True,False
5,003061226383,003061226383_80075103_Order form_978-0-220-044...,True,Television long seem capital catch care along.,0.839145,True,False
6,003061226383,003061226383_59879145_Order form_978-0-204-638...,True,Floor month exist officer.,0.666737,True,False
7,003061226383,003061226383_44230401_Order form_978-0-941325-...,True,Subject hear game experience story upon.,0.977807,True,False
8,003061227777,003061227777_96463321_other documents_978-1-96...,False,Yet arm six design.,0.607833,False,False
9,003061227777,003061227777_86071581_Order form_978-0-272-163...,True,Style rock education appear something church w...,0.630624,False,False

In [13]:
#check the condition, to be used by np.select()

[ (df_final['IsExecuted'] == False) | (df_final['QualityScore'] <0.81) ]

[0        True
 1       False
 2        True
 3        True
 4       False
         ...
 2064     True
 2065     True
 2066    False
 2067     True
 2068     True
 Length: 2069, dtype: bool]

In [14]:
# ===== Add an INVALID, column, which represents INVALID Contracts  =====
#- `IsExecuted==False`
#- `QualityScore<0.81

# create a list of conditions!
conditions = [ (df_final['IsExecuted'] == False) | (df_final['QualityScore'] <0.81) ]


df_final['INVALID'] = np.select(conditions, "1", "0")

In [15]:
df_final.head(10)

,CaseId,FileName,IsExecuted,OcrText,QualityScore,label_1,label_2,INVALID
0,003061226227,003061226227_12045631_Order form_978-1-67767-3...,False,Pressure style response character.,0.649292,False,False,1
1,003061226227,003061226227_78482906_other documents_978-0-25...,True,Wrong to very edge create.,0.919028,False,False,0
2,003061226227,003061226227_04034216_Order form_978-1-83411-5...,True,How serious approach another security fish inc...,0.707813,False,False,1
3,003061226383,003061226383_63912371_Contract Info Pack_978-0...,False,Soon especially boy thousand traditional.,0.873038,True,False,1
4,003061226383,003061226383_41775424_other documents_978-1-38...,True,Tax south say strategy hard between late.,0.991280,True,False,0
5,003061226383,003061226383_80075103_Order form_978-0-220-044...,True,Television long seem capital catch care along.,0.839145,True,False,0
6,003061226383,003061226383_59879145_Order form_978-0-204-638...,True,Floor month exist officer.,0.666737,True,False,1
7,003061226383,003061226383_44230401_Order form_978-0-941325-...,True,Subject hear game experience story upon.,0.977807,True,False,0
8,003061227777,003061227777_96463321_other documents_978-1-96...,False,Yet arm six design.,0.607833,False,False,1
9,003061227777,003061227777_86071581_Order form_978-0-272-163...,True,Style rock education appear something church w...,0.630624,False,False,1

In [16]:
## As per the requirments in README.md file: 
## 1- Get rid of OcrText for INVALID Contracts!

df_final.loc[df_final.INVALID == "1", "OcrText"] = ""

## 2- Add two new columns to specific index: ValidFileNames and InalidFileNames
df_final.insert(2, 'InalidFileNames', "")
df_final.insert(3, 'ValidFileNames', "")

In [17]:
print(df_final.shape)
df_final.head(10)

(2069, 10)

,CaseId,FileName,InalidFileNames,ValidFileNames,IsExecuted,OcrText,QualityScore,label_1,label_2,INVALID
0,003061226227,003061226227_12045631_Order form_978-1-67767-3...,,,False,,0.649292,False,False,1
1,003061226227,003061226227_78482906_other documents_978-0-25...,,,True,Wrong to very edge create.,0.919028,False,False,0
2,003061226227,003061226227_04034216_Order form_978-1-83411-5...,,,True,,0.707813,False,False,1
3,003061226383,003061226383_63912371_Contract Info Pack_978-0...,,,False,,0.873038,True,False,1
4,003061226383,003061226383_41775424_other documents_978-1-38...,,,True,Tax south say strategy hard between late.,0.991280,True,False,0
5,003061226383,003061226383_80075103_Order form_978-0-220-044...,,,True,Television long seem capital catch care along.,0.839145,True,False,0
6,003061226383,003061226383_59879145_Order form_978-0-204-638...,,,True,,0.666737,True,False,1
7,003061226383,003061226383_44230401_Order form_978-0-941325-...,,,True,Subject hear game experience story upon.,0.977807,True,False,0
8,003061227777,003061227777_96463321_other documents_978-1-96...,,,False,,0.607833,False,False,1
9,003061227777,003061227777_86071581_Order form_978-0-272-163...,,,True,,0.630624,False,False,1

In [18]:
## As per the "df_final_eg.png", contracts file names should be in InalidFileNames and ValidFileNames!

df_final.loc[df_final.INVALID == "1", "InalidFileNames"] = df_final.FileName
df_final.loc[df_final.INVALID == "0", "ValidFileNames"] = df_final.FileName

In [19]:
df_final.head(10)

,CaseId,FileName,InalidFileNames,ValidFileNames,IsExecuted,OcrText,QualityScore,label_1,label_2,INVALID
0,003061226227,003061226227_12045631_Order form_978-1-67767-3...,003061226227_12045631_Order form_978-1-67767-3...,,False,,0.649292,False,False,1
1,003061226227,003061226227_78482906_other documents_978-0-25...,,003061226227_78482906_other documents_978-0-25...,True,Wrong to very edge create.,0.919028,False,False,0
2,003061226227,003061226227_04034216_Order form_978-1-83411-5...,003061226227_04034216_Order form_978-1-83411-5...,,True,,0.707813,False,False,1
3,003061226383,003061226383_63912371_Contract Info Pack_978-0...,003061226383_63912371_Contract Info Pack_978-0...,,False,,0.873038,True,False,1
4,003061226383,003061226383_41775424_other documents_978-1-38...,,003061226383_41775424_other documents_978-1-38...,True,Tax south say strategy hard between late.,0.991280,True,False,0
5,003061226383,003061226383_80075103_Order form_978-0-220-044...,,003061226383_80075103_Order form_978-0-220-044...,True,Television long seem capital catch care along.,0.839145,True,False,0
6,003061226383,003061226383_59879145_Order form_978-0-204-638...,003061226383_59879145_Order form_978-0-204-638...,,True,,0.666737,True,False,1
7,003061226383,003061226383_44230401_Order form_978-0-941325-...,,003061226383_44230401_Order form_978-0-941325-...,True,Subject hear game experience story upon.,0.977807,True,False,0
8,003061227777,003061227777_96463321_other documents_978-1-96...,003061227777_96463321_other documents_978-1-96...,,False,,0.607833,False,False,1
9,003061227777,003061227777_86071581_Order form_978-0-272-163...,003061227777_86071581_Order form_978-0-272-163...,,True,,0.630624,False,False,1

#### To get rid of some additional uneeded columns: IsExecuted, QualityScore and INVALID!

In [20]:
#delete IsExecuted
if 'IsExecuted' in df_final.columns:
    del df_final['IsExecuted']

In [21]:
#delete QualityScore
if 'QualityScore' in df_final.columns:
    del df_final['QualityScore']

In [22]:
#delete INVALID
if 'INVALID' in df_final.columns:
    del df_final['INVALID']

In [23]:
#delete FileName
if 'FileName' in df_final.columns:
    del df_final['FileName']

In [24]:
print(df_final.shape)
df_final.head()

(2069, 6)

,CaseId,InalidFileNames,ValidFileNames,OcrText,label_1,label_2
0,003061226227,003061226227_12045631_Order form_978-1-67767-3...,,,False,False
1,003061226227,,003061226227_78482906_other documents_978-0-25...,Wrong to very edge create.,False,False
2,003061226227,003061226227_04034216_Order form_978-1-83411-5...,,,False,False
3,003061226383,003061226383_63912371_Contract Info Pack_978-0...,,,True,False
4,003061226383,,003061226383_41775424_other documents_978-1-38...,Tax south say strategy hard between late.,True,False

In [25]:
## Get a copy of df_final dataframe!

df_to_save = df_final.copy()
df_to_save.head()

,CaseId,InalidFileNames,ValidFileNames,OcrText,label_1,label_2
0,003061226227,003061226227_12045631_Order form_978-1-67767-3...,,,False,False
1,003061226227,,003061226227_78482906_other documents_978-0-25...,Wrong to very edge create.,False,False
2,003061226227,003061226227_04034216_Order form_978-1-83411-5...,,,False,False
3,003061226383,003061226383_63912371_Contract Info Pack_978-0...,,,True,False
4,003061226383,,003061226383_41775424_other documents_978-1-38...,Tax south say strategy hard between late.,True,False

In [26]:
## Use dataframe groupby with aggregation_functions!

#aggregation_functions = { 'InalidFileNames': ','.join, 'ValidFileNames': ','.join, 'OcrText':' '.join, 'label_1':'first', 'label_2':'first'}
aggregation_functions = { 'InalidFileNames':list, 'ValidFileNames': list, 'OcrText':' '.join, 'label_1':'first', 'label_2':'first'}

df_to_save = df_to_save.groupby(df_to_save['CaseId'], as_index=False).aggregate(aggregation_functions)

In [27]:
# Exapnd column width and see the results!

pd.set_option('max_colwidth', 120)

In [28]:
df_to_save.head()

,CaseId,InalidFileNames,ValidFileNames,OcrText,label_1,label_2
0,003061189006,[],[003061189006_69176036_Order form_978-1-62414-909-2.pdf],As difficult behavior her myself help.,True,False
1,003061189067,[],[003061189067_26173467_Order form_978-1-904782-31-5.pdf],Present can phone form.,True,False
2,003061189156,[],[003061189156_47966765_Contract Documents_978-0-317-34803-3.pdf],Section science difference success wish it wide.,False,False
3,003061189229,"[003061189229_69115288_Master contract_978-0-11-692367-7.pdf, ]","[, 003061189229_21094545_other documents_978-1-81560-843-8.pdf]",Accept sell leader herself if.,False,False
4,003061189242,[003061189242_91658807_other documents_978-0-7143-5356-2.pdf],[],,False,False

In [29]:
df_to_save.tail()

,CaseId,InalidFileNames,ValidFileNames,OcrText,label_1,label_2
1093,003061230659,[003061230659_72651667_Order form_978-0-661-06636-2.pdf],[],,True,False
1094,003061230710,"[003061230710_80047544_other documents_978-1-02-279791-8.pdf, 003061230710_59256366_Order form_978-1-209-37083-5.pdf]","[, ]",,True,False
1095,003061230728,"[003061230728_79408066_Master contract_978-0-14-891566-4.pdf, , 003061230728_56717174_Amendments_978-1-4471-4999-6.pdf]","[, 003061230728_74076581_Amendments_978-0-14-763189-3.pdf, ]",None attorney spend tend miss appear.,True,False
1096,003061230748,[003061230748_65193716_Contract Documents_978-0-9561206-8-7.pdf],[],,True,False
1097,003061230757,"[003061230757_84690982_other documents_978-0-10-551297-4.pdf, ]","[, 003061230757_72990476_Contract Documents_978-1-4943-5720-7.pdf]",Determine go network.,False,False

In [30]:
print(df_to_save.shape)
df_to_save.columns

(1098, 6)

Index(['CaseId', 'InalidFileNames', 'ValidFileNames', 'OcrText', 'label_1',
       'label_2'],
      dtype='object')

### To check the results (compare with "df_final_eg.png")

In [31]:
df_003061230659 = df_to_save[ (df_to_save['CaseId'] == "003061230659") == True]
df_003061230659

,CaseId,InalidFileNames,ValidFileNames,OcrText,label_1,label_2
1093,003061230659,[003061230659_72651667_Order form_978-0-661-06636-2.pdf],[],,True,False

In [32]:
df_003061230728 =  df_to_save[ (df_to_save['CaseId'] == "003061230728") == True]
df_003061230728

,CaseId,InalidFileNames,ValidFileNames,OcrText,label_1,label_2
1095,003061230728,"[003061230728_79408066_Master contract_978-0-14-891566-4.pdf, , 003061230728_56717174_Amendments_978-1-4471-4999-6.pdf]","[, 003061230728_74076581_Amendments_978-0-14-763189-3.pdf, ]",None attorney spend tend miss appear.,True,False

In [33]:
df_003061230728["InalidFileNames"]

1095    [003061230728_79408066_Master contract_978-0-14-891566-4.pdf, , 003061230728_56717174_Amendments_978-1-4471-4999-6.pdf]
Name: InalidFileNames, dtype: object

### Save the gzip to inside submit folder:

In [34]:
#df_to_save.to_csv(r"..\submit\df_final.gzip", index=False, compression="gzip")
df_to_save.to_csv(r"..\submit\df_final.gzip", compression="gzip")

<hr style="height:20px">

### The Running time in seconds!

In [35]:
## To print the Running time in seconds:

print("--- The Running time is: %s seconds ---" % (time.time() - start_time))

--- The Running time is: 3.520937919616699 seconds ---